// <auto-generated />
using MiQualityPMO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MiQualityPMO.Migrations
{
    [DbContext(typeof(MiQualityPMOContext))]
    [Migration("20220314015707_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiQualityPMO.Models.Mqaa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Factory")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FiscalYear")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("MiRate")
                        .HasColumnType("int");

                    b.Property<double>("PorRate")
                        .HasColumnType("double");

                    b.Property<string>("Quarter")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Mqaa");
                });
#pragma warning restore 612, 618
        }
    }
}
